### ISSUE TITLE
Create a package folder structure

### ISSUE THREAD

**Issue by ethnosdev** [ethnosdev/story_app#4]
In the `lib` folder, create the following structure:

```
lib/
    src/
        /widgets
    story_app.dart
```

The `src` folder is where the source code will go. For now these can be empty folders. Later we'll add widgets and other logic here.

story_app.dart is where we'll export the public widgets and classes. For now we can just leave this file empty.

**Comment by ethnosdev** [comment]
I don't think git supports committing empty folders. For now we can just add a blank placeholder file in the `widgets` folder so that it will show up in git.

**Comment by JuniorArt225** [comment]
> I don't think git supports committing empty folders. For now we can just add a blank placeholder file in the `widgets` folder so that it will show up in git.

D'accord

**Comment by JuniorArt225** [comment]
Okay

**Comment by ethnosdev** [comment]
> Okay

You can just use a thumbs up or some other emoji on a post to express agreement or understanding. If you write "Okay" or "D'accord" I get an email notification, but for a thumbs up I don't. When you use GitHub, save the email notifications for more important communication.
